{{- if .Values.deployments }}
{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ $deployment.name }}
 namespace: {{ $.Values.namespace }}
{{- template "default.labels" $ }}
{{- template "default.annotations" $ }}
spec:
 replicas: {{ $deployment.replicas }}
 selector:
  matchLabels:
   component: {{ $deployment.selectorValue }}
 template:
  metadata:
   labels:
    component: {{ $deployment.selectorValue }}
  spec:
   containers:
    - name: {{ $deployment.containerName }}
      image: {{ $deployment.imagePath }}
      ports: 
       - containerPort: {{ $deployment.containerPort }}
      envFrom:
       - configMapRef:
          name: {{ $deployment.selectorValue }}-configmap
       {{- if $deployment.secret }}
       - secretRef:
          name: {{ $deployment.secret.name }}
       {{- end}}
   imagePullSecrets:
    - name: gcr-json-key
{{- end }}
{{- end }}

